# Generated by Django 5.0.4 on 2024-10-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_name', models.CharField(max_length=100)),
                ('system_name', models.CharField(max_length=100)),
            ],
        ),
    ]
