# Generated by Django 5.0.4 on 2024-10-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_vendoroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='selected_vendor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='submit.vendoroption'),
        ),
    ]
