# Generated by Django 5.0.4 on 2024-09-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mark', '0001_initial'),
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessresult',
            name='guess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submit.guess'),
        ),
        migrations.AddField(
            model_name='guessresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mark.resulttype'),
        ),
    ]
