# Generated by Django 5.0.4 on 2024-10-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessResultError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_message', models.TextField()),
                ('guess_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mark.guessresult')),
            ],
        ),
    ]
