# Generated by Django 5.0.4 on 2024-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('explaination', models.TextField()),
                ('included_question', models.ManyToManyField(to='question.question')),
            ],
        ),
    ]
