# Generated by Django 5.0.4 on 2024-09-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explaination', models.TextField()),
                ('answer', models.TextField()),
                ('execution_limit_milisecond', models.DecimalField(decimal_places=0, default=1000, max_digits=10)),
            ],
        ),
    ]
